export const SOURCE_REGISTRY = [
    // -------------------------
    // RESALE / MARKETPLACES
    // -------------------------
    {
        id: "ebay",
        label: "eBay Browse API",
        group: "resale",
        type: "api",
        official: true,
        requiresEnv: ["EBAY_BEARER_TOKEN"],
        priority: 96,
        intents: ["resale", "product", "fashion", "sneakers", "electronics", "collectibles"],
        keywords: [
            "resale", "price", "sold", "used", "vintage", "sneaker", "shirt", "hoodie", "jacket",
            "raf", "rick owens", "supreme", "nike", "adidas", "depop", "grailed", "poshmark", "mercari",
        ],
    },
    {
        id: "depop",
        label: "Depop",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 88,
        intents: ["resale", "fashion", "streetwear", "vintage", "product"],
        keywords: ["depop", "vintage", "streetwear", "y2k", "archive", "shirt", "pants", "hoodie", "jacket"],
        buildUrl: (q) => `https://www.depop.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "poshmark",
        label: "Poshmark",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 83,
        intents: ["resale", "fashion", "product"],
        keywords: ["poshmark", "closet", "women", "men", "fashion", "handbag", "shoes", "shirt"],
        buildUrl: (q) => `https://poshmark.com/search?query=${encodeURIComponent(q)}&type=listings`,
    },
    {
        id: "grailed",
        label: "Grailed",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 91,
        intents: ["resale", "fashion", "streetwear", "designer", "product"],
        keywords: [
            "grailed", "designer", "archive", "raf simons", "rick owens", "helmut lang", "supreme",
            "stussy", "kapital", "undercover", "number nine", "chrome hearts",
        ],
        buildUrl: (q) => `https://www.grailed.com/shop/${encodeURIComponent(String(q).trim().replace(/\s+/g, "-"))}`,
    },
    {
        id: "mercari-us",
        label: "Mercari US",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 80,
        intents: ["resale", "product", "collectibles", "fashion"],
        keywords: ["mercari", "used", "resale", "collectible", "toy", "game", "clothes"],
        buildUrl: (q) => `https://www.mercari.com/search/?keyword=${encodeURIComponent(q)}`,
    },
    {
        id: "mercari-jp",
        label: "Mercari Japan",
        group: "resale-japan",
        type: "direct-site",
        official: true,
        priority: 90,
        intents: ["resale", "japan", "fashion", "proxy", "product"],
        keywords: ["mercari japan", "メルカリ", "japan", "jp", "raf simons", "archive", "proxy"],
        buildUrl: (q) => `https://jp.mercari.com/search?keyword=${encodeURIComponent(q)}`,
    },
    {
        id: "bunjang",
        label: "Bunjang / Korean resale",
        group: "resale-korea",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["resale", "korea", "fashion", "product"],
        keywords: ["bunjang", "bunjung", "bun jang", "korea", "korean", "streetwear", "archive"],
        buildUrl: (q) => `https://globalbunjang.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "zenmarket",
        label: "ZenMarket",
        group: "proxy-japan",
        type: "direct-site",
        official: true,
        priority: 75,
        intents: ["resale", "japan", "proxy", "auction", "product"],
        keywords: ["zenmarket", "japan proxy", "yahoo auctions", "rakuten", "mercari japan"],
        buildUrl: (q) => `https://zenmarket.jp/en/search.aspx?q=${encodeURIComponent(q)}`,
    },
    {
        id: "buyee",
        label: "Buyee Japan Proxy",
        group: "proxy-japan",
        type: "direct-site",
        official: true,
        priority: 74,
        intents: ["resale", "japan", "proxy", "auction", "product"],
        keywords: ["buyee", "japan proxy", "yahoo auctions", "mercari japan", "rakuma"],
        buildUrl: (q) => `https://buyee.jp/item/search/query/${encodeURIComponent(q)}`,
    },
    {
        id: "yahoo-auctions-jp",
        label: "Yahoo Auctions Japan",
        group: "proxy-japan",
        type: "direct-site",
        official: true,
        priority: 77,
        intents: ["resale", "japan", "auction", "proxy", "product"],
        keywords: ["yahoo auctions", "japan auction", "ヤフオク", "proxy"],
        buildUrl: (q) => `https://auctions.yahoo.co.jp/search/search?p=${encodeURIComponent(q)}`,
    },
    {
        id: "rakuten-jp",
        label: "Rakuten Japan",
        group: "retail-japan",
        type: "direct-site",
        official: true,
        priority: 68,
        intents: ["product", "japan", "retail", "fashion"],
        keywords: ["rakuten", "japan", "retail", "new"],
        buildUrl: (q) => `https://search.rakuten.co.jp/search/mall/${encodeURIComponent(q)}/`,
    },
    {
        id: "stockx",
        label: "StockX",
        group: "resale-verified",
        type: "direct-site",
        official: true,
        priority: 76,
        intents: ["resale", "product", "sneakers", "streetwear"],
        keywords: ["stockx", "sneaker", "jordan", "nike", "supreme", "market price"],
        buildUrl: (q) => `https://stockx.com/search?s=${encodeURIComponent(q)}`,
    },
    {
        id: "goat",
        label: "GOAT",
        group: "resale-verified",
        type: "direct-site",
        official: true,
        priority: 73,
        intents: ["resale", "product", "sneakers"],
        keywords: ["goat", "sneaker", "jordan", "nike", "adidas", "yeezy"],
        buildUrl: (q) => `https://www.goat.com/search?query=${encodeURIComponent(q)}`,
    },
    {
        id: "the-realreal",
        label: "The RealReal",
        group: "luxury-resale",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["resale", "fashion", "designer", "luxury"],
        keywords: ["realreal", "luxury", "designer", "consignment", "prada", "gucci", "raf"],
        buildUrl: (q) => `https://www.therealreal.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "vestiaire",
        label: "Vestiaire Collective",
        group: "luxury-resale",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["resale", "fashion", "designer", "luxury"],
        keywords: ["vestiaire", "designer", "luxury", "archive", "raf simons", "rick owens"],
        buildUrl: (q) => `https://www.vestiairecollective.com/search/?q=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // STREETWEAR / SNEAKER / CULTURE NEWS
    // -------------------------
    {
        id: "hypebeast",
        label: "Hypebeast",
        group: "streetwear-news",
        type: "direct-site",
        official: true,
        priority: 84,
        intents: ["streetwear", "fashion-news", "sneakers", "culture", "news"],
        keywords: ["hypebeast", "supreme", "nike", "adidas", "jordan", "streetwear", "drop", "release"],
        buildUrl: (q) => `https://hypebeast.com/search?s=${encodeURIComponent(q)}`,
    },
    {
        id: "highsnobiety",
        label: "Highsnobiety",
        group: "streetwear-news",
        type: "direct-site",
        official: true,
        priority: 76,
        intents: ["streetwear", "fashion-news", "sneakers", "culture"],
        keywords: ["highsnobiety", "streetwear", "fashion", "sneaker", "drop"],
        buildUrl: (q) => `https://www.highsnobiety.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "complex",
        label: "Complex",
        group: "streetwear-news",
        type: "direct-site",
        official: true,
        priority: 72,
        intents: ["streetwear", "music", "culture", "sneakers", "news"],
        keywords: ["complex", "sneaker", "music", "streetwear", "culture"],
        buildUrl: (q) => `https://www.complex.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "sneakernews",
        label: "Sneaker News",
        group: "sneaker-news",
        type: "direct-site",
        official: true,
        priority: 80,
        intents: ["sneakers", "fashion-news", "release", "streetwear"],
        keywords: ["sneaker", "jordan", "air max", "nike", "adidas", "release date"],
        buildUrl: (q) => `https://sneakernews.com/?s=${encodeURIComponent(q)}`,
    },
    {
        id: "solecollector",
        label: "Sole Collector",
        group: "sneaker-news",
        type: "direct-site",
        official: true,
        priority: 72,
        intents: ["sneakers", "release", "streetwear"],
        keywords: ["sneaker", "jordan", "nike", "adidas", "resale"],
        buildUrl: (q) => `https://solecollector.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "nicekicks",
        label: "Nice Kicks",
        group: "sneaker-news",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["sneakers", "release", "streetwear"],
        keywords: ["nice kicks", "sneaker", "jordan", "nike", "adidas", "release"],
        buildUrl: (q) => `https://www.nicekicks.com/?s=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // GENERAL NEWS
    // -------------------------
    {
        id: "cnn",
        label: "CNN",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["news", "breaking", "politics", "world", "business"],
        keywords: ["cnn", "news", "breaking", "politics", "world", "election", "business"],
        buildUrl: (q) => `https://www.cnn.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "nbc-news",
        label: "NBC News",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["news", "breaking", "politics", "world", "business"],
        keywords: ["nbc", "news", "breaking", "politics", "world", "election", "business"],
        buildUrl: (q) => `https://www.nbcnews.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "ap-news",
        label: "AP News",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 83,
        intents: ["news", "breaking", "world", "politics", "business"],
        keywords: ["ap news", "associated press", "breaking", "world", "politics"],
        buildUrl: (q) => `https://apnews.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "reuters",
        label: "Reuters",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 84,
        intents: ["news", "business", "markets", "world", "politics"],
        keywords: ["reuters", "markets", "business", "world news", "stocks", "economy"],
        buildUrl: (q) => `https://www.reuters.com/site-search/?query=${encodeURIComponent(q)}`,
    },
    {
        id: "bbc",
        label: "BBC",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["news", "world", "science", "technology", "business"],
        keywords: ["bbc", "world", "uk", "science", "technology"],
        buildUrl: (q) => `https://www.bbc.co.uk/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "npr",
        label: "NPR",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 72,
        intents: ["news", "world", "politics", "culture"],
        keywords: ["npr", "news", "politics", "world", "culture"],
        buildUrl: (q) => `https://www.npr.org/search?query=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // REFERENCE / ENCYCLOPEDIA
    // -------------------------
    {
        id: "wikipedia",
        label: "Wikipedia REST Search",
        group: "reference",
        type: "api",
        official: true,
        priority: 88,
        intents: ["research", "reference", "history", "science", "news", "developer", "general"],
        keywords: ["wikipedia", "wiki", "what is", "who is", "history", "definition", "overview"],
    },
    {
        id: "wikidata",
        label: "Wikidata Search",
        group: "reference",
        type: "api",
        official: true,
        priority: 72,
        intents: ["research", "reference", "data", "entity", "general"],
        keywords: ["wikidata", "entity", "identifier", "data", "structured"],
    },
    {
        id: "britannica",
        label: "Britannica",
        group: "reference",
        type: "direct-site",
        official: true,
        priority: 66,
        intents: ["research", "reference", "history", "science"],
        keywords: ["britannica", "encyclopedia", "history", "biography", "definition"],
        buildUrl: (q) => `https://www.britannica.com/search?query=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // SPACE / SCIENCE
    // -------------------------
    {
        id: "nasa-open",
        label: "NASA Open APIs",
        group: "space",
        type: "api",
        official: true,
        requiresEnv: ["NASA_API_KEY"],
        priority: 94,
        intents: ["space", "science", "nasa", "astronomy"],
        keywords: ["nasa", "apod", "mars", "rover", "asteroid", "space", "astronomy", "moon", "launch"],
    },
    {
        id: "nasa-images",
        label: "NASA Image and Video Library",
        group: "space",
        type: "api",
        official: true,
        priority: 86,
        intents: ["space", "science", "image", "video"],
        keywords: ["nasa image", "space image", "mars photo", "moon photo", "telescope"],
    },
    {
        id: "space-com",
        label: "Space.com",
        group: "space-news",
        type: "rss-or-direct",
        official: true,
        priority: 83,
        intents: ["space", "science", "astronomy", "space-news", "news"],
        keywords: ["space.com", "space", "astronomy", "rocket", "launch", "nasa", "moon", "mars"],
        rss: "https://www.space.com/feeds/all",
        buildUrl: (q) => `https://www.space.com/search?searchTerm=${encodeURIComponent(q)}`,
    },
    {
        id: "spaceflight-now",
        label: "Spaceflight Now",
        group: "space-news",
        type: "direct-site",
        official: true,
        priority: 76,
        intents: ["space", "launch", "rocket", "news"],
        keywords: ["spaceflight", "rocket launch", "falcon", "starship", "ula", "ariane"],
        buildUrl: (q) => `https://spaceflightnow.com/?s=${encodeURIComponent(q)}`,
    },
    {
        id: "spacex",
        label: "SpaceX",
        group: "space-official",
        type: "direct-site",
        official: true,
        priority: 74,
        intents: ["space", "launch", "rocket"],
        keywords: ["spacex", "starship", "falcon", "dragon", "launch"],
        buildUrl: (q) => `https://www.spacex.com/search/?search=${encodeURIComponent(q)}`,
    },
    {
        id: "esa",
        label: "European Space Agency",
        group: "space-official",
        type: "direct-site",
        official: true,
        priority: 72,
        intents: ["space", "science", "research", "news"],
        keywords: ["esa", "european space agency", "space", "mars", "earth observation"],
        buildUrl: (q) => `https://www.esa.int/esearch?q=${encodeURIComponent(q)}`,
    },
    {
        id: "arxiv",
        label: "arXiv",
        group: "science",
        type: "api",
        official: true,
        priority: 84,
        intents: ["science", "research", "paper", "ai", "physics", "space", "developer"],
        keywords: ["paper", "research", "arxiv", "machine learning", "physics", "astronomy", "computer science"],
    },
    {
        id: "phys-org",
        label: "Phys.org",
        group: "science-news",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["science", "research", "space", "news"],
        keywords: ["phys.org", "science", "physics", "biology", "space", "research"],
        buildUrl: (q) => `https://phys.org/search/?search=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // DEV / DOCS / COMMUNITY
    // -------------------------
    {
        id: "github",
        label: "GitHub Repository Search",
        group: "developer",
        type: "api",
        official: true,
        priority: 84,
        intents: ["developer", "code", "repo", "api", "open-source"],
        keywords: ["github", "repo", "source code", "open source", "react", "python", "javascript", "api"],
    },
    {
        id: "npm",
        label: "npm Package Search",
        group: "developer",
        type: "api",
        official: true,
        priority: 78,
        intents: ["developer", "code", "package", "javascript", "node"],
        keywords: ["npm", "package", "node", "react", "javascript", "library"],
    },
    {
        id: "mdn",
        label: "MDN Web Docs",
        group: "developer-docs",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["developer", "javascript", "web", "docs", "api"],
        keywords: ["mdn", "javascript", "web api", "css", "html", "browser"],
        buildUrl: (q) => `https://developer.mozilla.org/en-US/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "cloudflare-docs",
        label: "Cloudflare Docs",
        group: "developer-docs",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["developer", "cloudflare", "worker", "pages", "docs"],
        keywords: ["cloudflare", "worker", "pages", "r2", "durable objects", "cdn"],
        buildUrl: (q) => `https://developers.cloudflare.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "reddit",
        label: "Reddit",
        group: "community",
        type: "api-or-json",
        official: true,
        priority: 76,
        intents: ["community", "discussion", "reviews", "resale", "tech", "developer"],
        keywords: ["reddit", "discussion", "review", "opinion", "depop", "grailed", "supreme", "tech support"],
    },
    {
        id: "hackernews",
        label: "Hacker News",
        group: "developer",
        type: "api",
        official: true,
        priority: 74,
        intents: ["developer", "startup", "tech", "ai", "news"],
        keywords: ["startup", "programming", "developer", "ai", "hacker news", "software"],
    },
];

export function getSourceById(id) {
    return SOURCE_REGISTRY.find((source) => source.id === id) || null;
}
