export const SOURCE_REGISTRY = [
    // -------------------------
    // RESALE / MARKETPLACES
    // -------------------------
    {
        id: "ebay",
        label: "eBay",
        group: "resale",
        type: "api",
        official: true,
        requiresEnv: ["EBAY_BEARER_TOKEN"],
        priority: 95,
        intents: ["resale", "product", "fashion", "sneakers", "electronics", "collectibles"],
        keywords: [
            "resale", "price", "sold", "used", "vintage", "sneaker", "shirt",
            "hoodie", "jacket", "raf", "rick owens", "supreme", "nike", "adidas",
            "depop", "grailed", "poshmark", "mercari"
        ],
    },
    {
        id: "depop",
        label: "Depop",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 86,
        intents: ["resale", "fashion", "streetwear", "vintage"],
        keywords: ["depop", "vintage", "streetwear", "y2k", "archive", "shirt", "pants", "hoodie", "jacket"],
        buildUrl: (q) => `https://www.depop.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "poshmark",
        label: "Poshmark",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 82,
        intents: ["resale", "fashion", "product"],
        keywords: ["poshmark", "closet", "women", "men", "fashion", "handbag", "shoes", "shirt"],
        buildUrl: (q) => `https://poshmark.com/search?query=${encodeURIComponent(q)}&type=listings`,
    },
    {
        id: "grailed",
        label: "Grailed",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 88,
        intents: ["resale", "fashion", "streetwear", "designer"],
        keywords: [
            "grailed", "designer", "archive", "raf simons", "rick owens", "helmut lang",
            "supreme", "stussy", "kapital", "undercover", "number nine"
        ],
        buildUrl: (q) => `https://www.grailed.com/shop/${encodeURIComponent(q.replace(/\s+/g, "-"))}`,
    },
    {
        id: "mercari-us",
        label: "Mercari US",
        group: "resale",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["resale", "product", "collectibles"],
        keywords: ["mercari", "used", "resale", "collectible", "toy", "game", "clothes"],
        buildUrl: (q) => `https://www.mercari.com/search/?keyword=${encodeURIComponent(q)}`,
    },
    {
        id: "mercari-jp",
        label: "Mercari Japan",
        group: "resale-japan",
        type: "direct-site",
        official: true,
        priority: 84,
        intents: ["resale", "japan", "fashion", "proxy"],
        keywords: ["mercari japan", "メルカリ", "japan", "jp", "raf simons", "archive", "proxy"],
        buildUrl: (q) => `https://jp.mercari.com/search?keyword=${encodeURIComponent(q)}`,
    },
    {
        id: "bunjang",
        label: "Bunjang / Korean resale",
        group: "resale-korea",
        type: "direct-site",
        official: true,
        priority: 74,
        intents: ["resale", "korea", "fashion"],
        keywords: ["bunjang", "bun jang", "korea", "korean", "streetwear", "archive"],
        buildUrl: (q) => `https://globalbunjang.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "zenmarket",
        label: "ZenMarket",
        group: "proxy-japan",
        type: "direct-site",
        official: true,
        priority: 73,
        intents: ["resale", "japan", "proxy", "auction"],
        keywords: ["zenmarket", "japan proxy", "yahoo auctions", "rakuten", "mercari japan"],
        buildUrl: (q) => `https://zenmarket.jp/en/search.aspx?q=${encodeURIComponent(q)}`,
    },
    {
        id: "yahoo-auctions-jp",
        label: "Yahoo Auctions Japan",
        group: "proxy-japan",
        type: "direct-site",
        official: true,
        priority: 72,
        intents: ["resale", "japan", "auction", "proxy"],
        keywords: ["yahoo auctions", "japan auction", "ヤフオク", "proxy"],
        buildUrl: (q) => `https://auctions.yahoo.co.jp/search/search?p=${encodeURIComponent(q)}`,
    },
    {
        id: "rakuten-jp",
        label: "Rakuten Japan",
        group: "retail-japan",
        type: "direct-site",
        official: true,
        priority: 65,
        intents: ["product", "japan", "retail"],
        keywords: ["rakuten", "japan", "retail", "new"],
        buildUrl: (q) => `https://search.rakuten.co.jp/search/mall/${encodeURIComponent(q)}/`,
    },

    // -------------------------
    // STREETWEAR / CULTURE NEWS
    // -------------------------
    {
        id: "hypebeast",
        label: "Hypebeast",
        group: "streetwear-news",
        type: "direct-site",
        official: true,
        priority: 83,
        intents: ["streetwear", "fashion-news", "sneakers", "culture"],
        keywords: ["hypebeast", "supreme", "nike", "adidas", "jordan", "streetwear", "drop", "release"],
        buildUrl: (q) => `https://hypebeast.com/search?s=${encodeURIComponent(q)}`,
    },
    {
        id: "complex",
        label: "Complex",
        group: "streetwear-news",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["streetwear", "music", "culture", "sneakers"],
        keywords: ["complex", "sneaker", "music", "streetwear", "culture"],
        buildUrl: (q) => `https://www.complex.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "sneakernews",
        label: "Sneaker News",
        group: "sneaker-news",
        type: "direct-site",
        official: true,
        priority: 78,
        intents: ["sneakers", "fashion-news", "release"],
        keywords: ["sneaker", "jordan", "air max", "nike", "adidas", "release date"],
        buildUrl: (q) => `https://sneakernews.com/?s=${encodeURIComponent(q)}`,
    },
    {
        id: "solecollector",
        label: "Sole Collector",
        group: "sneaker-news",
        type: "direct-site",
        official: true,
        priority: 70,
        intents: ["sneakers", "release"],
        keywords: ["sneaker", "jordan", "nike", "adidas", "resale"],
        buildUrl: (q) => `https://solecollector.com/search?q=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // GENERAL NEWS
    // -------------------------
    {
        id: "cnn",
        label: "CNN",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 76,
        intents: ["news", "breaking", "politics", "world", "business"],
        keywords: ["cnn", "news", "breaking", "politics", "world", "election", "business"],
        buildUrl: (q) => `https://www.cnn.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "nbc-news",
        label: "NBC News",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 76,
        intents: ["news", "breaking", "politics", "world", "business"],
        keywords: ["nbc", "news", "breaking", "politics", "world", "election", "business"],
        buildUrl: (q) => `https://www.nbcnews.com/search/?q=${encodeURIComponent(q)}`,
    },
    {
        id: "ap-news",
        label: "AP News",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 77,
        intents: ["news", "breaking", "world", "politics"],
        keywords: ["ap news", "associated press", "breaking", "world", "politics"],
        buildUrl: (q) => `https://apnews.com/search?q=${encodeURIComponent(q)}`,
    },
    {
        id: "reuters",
        label: "Reuters",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 77,
        intents: ["news", "business", "markets", "world", "politics"],
        keywords: ["reuters", "markets", "business", "world news", "stocks", "economy"],
        buildUrl: (q) => `https://www.reuters.com/site-search/?query=${encodeURIComponent(q)}`,
    },
    {
        id: "bbc",
        label: "BBC",
        group: "news",
        type: "direct-site",
        official: true,
        priority: 74,
        intents: ["news", "world", "science", "technology"],
        keywords: ["bbc", "world", "uk", "science", "technology"],
        buildUrl: (q) => `https://www.bbc.co.uk/search?q=${encodeURIComponent(q)}`,
    },

    // -------------------------
    // SPACE / SCIENCE
    // -------------------------
    {
        id: "nasa-open",
        label: "NASA Open APIs",
        group: "space",
        type: "api",
        official: true,
        requiresEnv: ["NASA_API_KEY"],
        priority: 93,
        intents: ["space", "science", "nasa", "astronomy"],
        keywords: ["nasa", "apod", "mars", "rover", "asteroid", "space", "astronomy", "moon", "launch"],
    },
    {
        id: "nasa-images",
        label: "NASA Image and Video Library",
        group: "space",
        type: "api",
        official: true,
        priority: 84,
        intents: ["space", "science", "image", "video"],
        keywords: ["nasa image", "space image", "mars photo", "moon photo", "telescope"],
    },
    {
        id: "space-com",
        label: "Space.com",
        group: "space-news",
        type: "rss-or-direct",
        official: true,
        priority: 82,
        intents: ["space", "science", "astronomy", "space-news"],
        keywords: ["space.com", "space", "astronomy", "rocket", "launch", "nasa", "moon", "mars"],
        rss: "https://www.space.com/feeds/all",
        buildUrl: (q) => `https://www.space.com/search?searchTerm=${encodeURIComponent(q)}`,
    },
    {
        id: "spaceflight-now",
        label: "Spaceflight Now",
        group: "space-news",
        type: "direct-site",
        official: true,
        priority: 74,
        intents: ["space", "launch", "rocket"],
        keywords: ["spaceflight", "rocket launch", "falcon", "starship", "ula", "ariane"],
        buildUrl: (q) => `https://spaceflightnow.com/?s=${encodeURIComponent(q)}`,
    },
    {
        id: "arxiv",
        label: "arXiv",
        group: "science",
        type: "api",
        official: true,
        priority: 83,
        intents: ["science", "research", "paper", "ai", "physics", "space"],
        keywords: ["paper", "research", "arxiv", "machine learning", "physics", "astronomy", "computer science"],
    },

    // -------------------------
    // DEV / COMMUNITY
    // -------------------------
    {
        id: "github",
        label: "GitHub",
        group: "developer",
        type: "api",
        official: true,
        priority: 82,
        intents: ["developer", "code", "repo", "api"],
        keywords: ["github", "repo", "source code", "open source", "react", "python", "javascript", "api"],
    },
    {
        id: "reddit",
        label: "Reddit",
        group: "community",
        type: "api-or-json",
        official: true,
        priority: 78,
        intents: ["community", "discussion", "reviews", "resale", "tech"],
        keywords: ["reddit", "discussion", "review", "opinion", "depop", "grailed", "supreme", "tech support"],
    },
    {
        id: "hackernews",
        label: "Hacker News",
        group: "developer",
        type: "api",
        official: true,
        priority: 75,
        intents: ["developer", "startup", "tech", "ai"],
        keywords: ["startup", "programming", "developer", "ai", "hacker news", "software"],
    }
];